export const actions = {
    FILTER_STUDENTS: 'FILTER_STUDENTS',

    GET_STUDENTS_REQUEST: 'GET_STUDENTS_REQUEST',
    GET_STUDENTS_SUCCESS: 'GET_STUDENTS_SUCCESS',
    GET_STUDENTS_FAILURE: 'GET_STUDENTS_FAILURE',
    VERIFY_STUDENT_REQUEST: 'VERIFY_STUDENT_REQUEST',
    VERIFY_STUDENT_SUCCESS: 'VERIFY_STUDENT_SUCCESS',
    VERIFY_STUDENT_FAILURE: 'VERIFY_STUDENT_FAILURE',
    SET_SELECTED_ID: 'SET_SELECTED_ID',
}