export const actions = {
    FILTER_STUDENTS: 'FILTER_STUDENTS',

    GET_STUDENTS_REQUEST: 'GET_STUDENTS_REQUEST',
    GET_STUDENTS_SUCCESS: 'GET_STUDENTS_SUCCESS',
    GET_STUDENTS_FAILURE: 'GET_STUDENTS_FAILURE',
}