export const actions = {
  VALIDATE_CONVERSATION: "VALIDATE_CONVERSATION",
  VALIDATE_CONVERSATION_SUCCESS: "VALIDATE_CONVERSATION_SUCCESS",
  VALIDATE_CONVERSATION_FAIL: "VALIDATE_CONVERSATION_FAIL",
  START_CONVERSATION: "START_CONVERSATION",
  START_CONVERSATION_SUCCESS: "START_CONVERSATION_SUCCESS",
  START_CONVERSATION_FAIL: "START_CONVERSATION_FAIL",
  UPDATE_MESSAGE: "UPDATE_MESSAGE",
};
