export const initialState = {
  selectedUser: null,
  socketActions: {
    join: "join",
    successJoin: "successJoin",
    checkUserStatus: "checkUserStatus",
    sendUserStatus: "sendUserStatus",
    sendMessage: "sendMessage",
    receiveMessage: "receiveMessage",
    requestUsersStatus: "requestUsersStatus",
    sendUsersStatus: "sendUsersStatus",
    userHasDisconnected: "userHasDisconnected",
    userHasConnected: "userHasConnected",
    callUser: "callUser",
    rejectedCall: "rejectedCall",
    endedCall: "endedCall",
  },
  userDataSocket: null,
  showModalCall: false,
  useToCallData: null,

  caller: null,
  receivingCall: false,
  callEnded: false,
  callAccepted: false,
  rejectedCall: false,
  calling: false,
};
