export const actions = {
  UPDATE_QUERY: "UPDATE_QUERY",
  SEARCH_REQUEST: "SEARCH_REQUEST",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  SEARCH_FAIL: "SEARCH_FAIL",
  SET_SELECTED_USER: "SET_SELECTED_USER",
};
